steps:
  # Step 1: Get credentials for the GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'ey-devops-cluster'
      - '--region'
      - 'us-central1'
      
  # Step2: Set up kubectl
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ey-devops-cluster'
      - KUBECONFIG=/workspace/.kube/config  
      
  # Step 3: Apply the blue deployment YAML to the GKE cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes/blue-deployment.yaml'
      - '-f'
      - 'kubernetes/service.yaml'
options:
  logging: CLOUD_LOGGING_ONLY
