steps:
# This step deploys the new version of our container image
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
 # - 'kubernetes/blue-deployment.yaml'
  - 'kubernetes/green-deployment.yaml'
  - '-f'
  - 'kubernetes/service.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ey-devops-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
