steps:
  # Step 1: Get credentials for the GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'ey-devops-cluster'
      - '--region'
      - 'us-central1'

  # Step 2: Apply the blue deployment YAML to the GKE cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes/blue-deployment.yaml'
options:
  logging: CLOUD_LOGGING_ONLY
